export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

export const GET_DEPOSIT = 'GET_DEPOSIT';
export const GET_DEPOSIT_SUCCESS = 'GET_DEPOSIT_SUCCESS';
export const GET_DEPOSIT_FAILED = 'GET_DEPOSIT_FAILED';

export const GET_SWAP = 'GET_SWAP';
export const GET_SWAP_SUCCESS = 'GET_SWAP_SUCCESS';
export const GET_SWAP_FAILED = 'GET_SWAP_FAILED';

export const GET_WITHDRAW = 'GET_WITHDRAW';
export const GET_WITHDRAW_SUCCESS = 'GET_WITHDRAW_SUCCESS';
export const GET_WITHDRAW_FAILED = 'GET_WITHDRAW_FAILED';